/*
 * generated by Xtext 2.13.0
 */
package org.pzot.syntax.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.pzot.syntax.PZotRuntimeModule
import org.pzot.syntax.PZotStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class PZotIdeSetup extends PZotStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new PZotRuntimeModule, new PZotIdeModule))
	}
	
}
